#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim:ts=4:sw=4:softtabstop=4:smarttab:expandtab

from __future__ import (unicode_literals, division, absolute_import,
                        print_function)

import os
import inspect
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))

# pylupdate command must be in PATH
if __name__ == '__main__':
    os.chdir(SCRIPT_DIR)
    cmd = ['pylupdate5', 'translations.pro']
    subprocess.check_call(cmd)
        